spring:
  cloud:
    function:
      definition: studentManagementServiceSink
    stream:
      bindings:
        courseManagementServiceEventProduce-in-0:
          destination: courseServiceEvent
        studentManagementServiceSink-in-0:
          destination: studentSerivceEvent
          group: courseManagementService
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /console-h2
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
server:
  port: 8081
url:
  studentService: http://127.0.0.1:8080