spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /console-h2
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default